title: Discrete Optimization in Python
author: Yannik Frisch
only_build_toc_files: true

sphinx:
  config:
    root_doc: docs/index
    master_doc: docs/index

execute:
  execute_notebooks: "force"
  timeout: 300

repository:
  url: https://github.com/YFrisch/Discrete-Optimization-In-Python
  branch: master

html:
  use_repository_button: true
  use_issues_button: true

exclude_patterns:
  - ".venv"
  - ".venv/**"
  - "**/.venv/**"
  - "**/__pycache__/**"
  - "**/.pytest_cache/**"
  - "**/.ipynb_checkpoints/**"
  - "_build/**"
  - "docs/_build/**"
  - ".git/**"